baseURL = 'https://amicidelperu.it/'
languageCode = 'it-it'
title = 'Amici Del Perù'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

resourceDir = "../resources"

DefaultContentLanguage = "it"
SectionPagesMenu = "main"

# this is set low for demonstrating with dummy content. Set to a higher number
# Paginate = 3
googleAnalytics = "G-G22JF4L9TD"
enableRobotsTXT = true

#[languages]
#  [languages.en]
#    title = "Ananke"
#    weight = 1
#    contentDir = "content/en"
#    # languageDirection = 'rtl' for Right-To-Left languages
#  [languages.fr]
#    title = "Ananke Fr"
#    weight = 2
#    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
#  text_color = ""
#  author = ""
  favicon = "images/logo_64.ico"
# site_logo = "images/logo.svg"
#  description = "The last theme you'll ever need. Maybe."
#  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-washed-green"
#  recent_posts_number = 3
  footer = "VAT IT01262830399 - CF 90010520394 -  Via Pagani 5 - 48018 - Faenza(RA)"

#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"